library("data.table")
MyData<-fread("data/household_power_consumption.txt",sep=";",header=TRUE, stringsAsFactors = TRUE, na.strings="?")  
##head(MyData)
power_data_set <- as.data.frame(MyData)
dates <- as.Date(power_data_set$Date,"%d/%m/%Y")
##head(dates)
dataset_household_power <- cbind(power_data_set, dates)
data_subset <- dataset_household_power[dates=="2007-02-01"|dates=="2007-02-02",]
head(data_subset)
##tail(data_subset)
##times <- strptime(data_subset$Time, format="")
##times <- as.POSIXct(data_subset$Time, format = "%H:%M:%S")
##head(times)

time_dim<-paste(as.Date(data_subset$Date,"%d/%m/%Y"),strftime(strptime(data_subset$Time,format="%H:%M:%S"),'%H:%M:%S'))
##head(time_dim)
##time_dim <- strptime(power_data_set$Time,"%H:%M:%S")
##head(time_dim)
##time_dim2<-strftime(time_dim, '%H:%M:%S')
##head(time_dim2)
data_sub_dt <- cbind(data_subset, time_dim)
head(data_sub_dt)
plot_data <- transform(data_sub_dt, time_dim = factor(weekdays(as.Date(data_sub_dt$time_dim))))
##boxplot(Ozone ~ Month, airquality, xlab = "Month", ylab = "Ozone (ppb)")
##data_sub_dt <- transform(data_sub_dt, time_dim=factor(weekdays(as.Date(data_sub_dt$time_dim))))
time_dim1 <- weekdays(as.Date(data_sub_dt$time_dim))
data_sub_dt1 <- cbind(data_sub_dt, time_dim1)
data_sub_dt1 <- transform(data_sub_dt1, time_dim1=factor(time_dim1))
##lines(data_sub_dt1$time_dim1, data_sub_dt$Global_active_power, type="l", xlab="data_sub_dt1$time_dim1")
hist(data_sub_dt$Global_active_power,col="red",xlab="Global Active Power (kilowatts)",ylab="Frequency")

##plot(data_sub_dt1$time_dim, data_sub_dt$Global_active_power, type="l", xlab="Weekdays", ylab="Global Active Power (Kilowatts)")

##plot(data_sub_dt$time_dim,data_sub_dt$Sub_metering_1,type="l",col="black", ylab="Energy Sub Metering")
##lines(data_sub_dt$time_dim,data_sub_dt$Sub_metering_2,type="l",col="blue")
##lines(data_sub_dt$time_dim,data_sub_dt$Sub_metering_3,type="l",col="red")
##legend("topright",pch="_", col = c("black","blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))

##par(mfrow = c(2,2), mar = c(4, 4, 2, 1), oma = c(0, 0, 2, 0))

##plot(data_sub_dt1$time_dim, data_sub_dt$Global_active_power, type="l", xlab="Weekdays", ylab="Global Active Power (kwh)")
##plot(data_sub_dt1$time_dim, data_sub_dt$Voltage, type="l", xlab="Weekdays", ylab="Voltage")
##plot(data_sub_dt$time_dim,data_sub_dt$Sub_metering_1,type="l",col="black", ylab="Energy Sub Metering")
##lines(data_sub_dt$time_dim,data_sub_dt$Sub_metering_2,type="l",col="blue")
##lines(data_sub_dt$time_dim,data_sub_dt$Sub_metering_3,type="l",col="red")
##legend("topright",pch="_", col = c("black","blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))

##plot(data_sub_dt1$time_dim, data_sub_dt$Global_reactive_power, type="l", xlab="Weekdays", ylab="Global Reactive Power (kwh)")
